"""Add collections, exam_papers, user_attempts tables

Revision ID: 19482b1b5a4b
Revises: 7e7a776a3f8d
Create Date: 2025-12-22 20:15:45.511477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19482b1b5a4b'
down_revision: Union[str, Sequence[str], None] = '7e7a776a3f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('exam_name', sa.String(length=100), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('question_data', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_papers_exam_name'), 'exam_papers', ['exam_name'], unique=False)
    op.create_index(op.f('ix_exam_papers_id'), 'exam_papers', ['id'], unique=False)
    op.create_index(op.f('ix_exam_papers_title'), 'exam_papers', ['title'], unique=False)
    op.create_index(op.f('ix_exam_papers_year'), 'exam_papers', ['year'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('user_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('user_identifier', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_attempts_id'), 'user_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_user_attempts_paper_id'), 'user_attempts', ['paper_id'], unique=False)
    op.create_index(op.f('ix_user_attempts_user_identifier'), 'user_attempts', ['user_identifier'], unique=False)
    op.create_table('collection_files',
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'file_id')
    )
    op.add_column('quiz_questions', sa.Column('question_metadata', sa.JSON(), nullable=True))
    op.add_column('quiz_questions', sa.Column('submitted', sa.Boolean(), nullable=False))
    op.add_column('quiz_questions', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quiz_questions', sa.Column('user_responses', sa.JSON(), nullable=True))
    op.add_column('quiz_questions', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('uploaded_files', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('uploaded_files', sa.Column('indexing_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'indexing_status')
    op.drop_column('uploaded_files', 'file_type')
    op.drop_column('quiz_questions', 'score')
    op.drop_column('quiz_questions', 'user_responses')
    op.drop_column('quiz_questions', 'submitted_at')
    op.drop_column('quiz_questions', 'submitted')
    op.drop_column('quiz_questions', 'question_metadata')
    op.drop_table('collection_files')
    op.drop_index(op.f('ix_user_attempts_user_identifier'), table_name='user_attempts')
    op.drop_index(op.f('ix_user_attempts_paper_id'), table_name='user_attempts')
    op.drop_index(op.f('ix_user_attempts_id'), table_name='user_attempts')
    op.drop_table('user_attempts')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_exam_papers_year'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_title'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_id'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_exam_name'), table_name='exam_papers')
    op.drop_table('exam_papers')
    # ### end Alembic commands ###
