"""Add multi-provider authentication fields

Revision ID: e9f8a7b6c5d4
Revises: db1375176257
Create Date: 2025-12-29 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f8a7b6c5d4'
down_revision: Union[str, Sequence[str], None] = 'db1375176257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to users table for multi-provider authentication
    op.add_column('users', sa.Column('provider_type', sa.String(), nullable=False, server_default='custom'))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))

    # Create indexes for new columns
    op.create_index(op.f('ix_users_provider_type'), 'users', ['provider_type'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_provider_type'), table_name='users')

    # Drop columns
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'provider_type')
    # ### end Alembic commands ###